# Describes the format for available services for KEBA charging staitons

start:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    rfid:
      selector:
        text:
    rfid_class:
      selector:
        text:

stop:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    rfid:
      selector:
        text:

set_energy:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    energy:
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: kWh

set_current:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    current:
      required: true
      default: 6
      selector:
        number:
          min: 6
          max: 63
          step: 0.001
          unit_of_measurement: A
    delay:
      default: 0
      selector:
        number:
          min: 0
          max: 860400
          step: 1
          unit_of_measurement: seconds

set_failsafe:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    mode:
      default: true
      selector:
        boolean:
    timeout:
      default: 30
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: seconds
    fallback_value:
      default: 6
      selector:
        number:
          min: 6
          max: 63
          step: 0.001
          unit_of_measurement: A
    persist:
      default: false
      selector:
        boolean:

set_charging_power:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    power:
      required: true
      default: 11
      selector:
        number:
          min: 0
          max: 22
          step: 0.1
          unit_of_measurement: kW
    round_up:
      required: true
      default: false
      selector:
        boolean:
    stop_below_6_ampere:
      required: true
      default: true
      selector:
        boolean:

set_output:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    out:
      required: true
      default: 0
      selector:
        number:

x2src:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    source:
      required: true
      selector:
        number:
          min: 0
          max: 4
          step: 1

x2:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: keba
    three_phases:
      required: true
      selector:
        boolean:
